### ISSUE TITLE
Old image slideshow

### ISSUE THREAD

**Issue by SmithPeder** [abakus-ntnu/jubileum#26]
We have a large archive of old photos. It would be really cool to create a slideshow where one could scroll through old photos.

Creating the slideshow itself should be easy. The "challenge" will be to create a slideshow that does not require the user to fetch all the "hundreds" of images at once.

**Comment by danielyanghansen** [comment]
A few questions:
1: Is the slideshow supposed to show only one image at a time? (with preview to index adjacent images)
2: Are the images indexed in an easily hashable way? Or at least in some way consistently in order
I imagine the easiest solution is to iterate over a generated dictionary with image index/order as the key.
