### ISSUE TITLE
Dropdown

### ISSUE THREAD

**Issue by SmithPeder** [abakus-ntnu/jubileum#50]
I don't think we need this dropdown. Can't we just have the text here? It's quite short :) 
![image](https://user-images.githubusercontent.com/23152018/151706760-85de0b66-97e4-4e56-ae61-97636dce3d36.png)
![image](https://user-images.githubusercontent.com/23152018/151706777-46127acd-b981-4ebe-ae8c-be125452c5b5.png)

**Comment by eikhr** [comment]
Done in #68
